name: Build and Release PDF (Nix)

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Needed to create releases
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Build PDF with Nix
        run: |
          nix develop --command pdflatex -interaction=nonstopmode main.tex
          # Run twice to ensure proper references
          nix develop --command pdflatex -interaction=nonstopmode main.tex
      
      - name: Rename PDF with version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            mv main.pdf "ml-rl-presentation-${VERSION}.pdf"
            echo "PDF_NAME=ml-rl-presentation-${VERSION}.pdf" >> $GITHUB_ENV
          else
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            mv main.pdf "ml-rl-presentation-${TIMESTAMP}.pdf"
            echo "PDF_NAME=ml-rl-presentation-${TIMESTAMP}.pdf" >> $GITHUB_ENV
          fi
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PDF_NAME }}
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          body: |
            ## Machine Learning and Reinforcement Learning Presentation
            
            This release contains the PDF presentation about ML & RL beyond LLMs.
            
            ### What's included:
            - 📄 PDF presentation slides
            - 🎯 ML basics and neural architectures
            - 🤖 Key ML domains outside of LLMs
            - 🎮 Reinforcement learning applications
            - 🔧 RLHF implementation details
            
            Download the PDF below to view the presentation.
      
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: presentation-pdf
          path: ${{ env.PDF_NAME }}
          retention-days: 30